### ISSUE TITLE
Concurrent write on websocket

### ISSUE THREAD

**Issue by ThomasObenaus** [supplyon/gremcos#20]
```
panic: concurrent write to websocket connection
        panic: concurrent write to websocket connection

goroutine 45 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc000252510, 0xc0003abb01, 0x0, 0x0, 0x0, 0x7f722e15c008, 0x0)
        /home/user/work/golang/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:610 +0x612
github.com/gorilla/websocket.(*messageWriter).Close(0xc000252510, 0x0, 0xc00057b7c8)
        /home/user/work/golang/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:724 +0x62
github.com/gorilla/websocket.(*Conn).beginMessage(0xc00030c9a0, 0xc0003abb00, 0x8, 0x43033c, 0xc00057b840)
        /home/user/work/golang/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:473 +0x284
github.com/gorilla/websocket.(*Conn).NextWriter(0xc00030c9a0, 0x8, 0x0, 0xc00005a380, 0x7f722e15c008, 0x0)
        /home/user/work/golang/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:513 +0x53
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc00030c9a0, 0x8, 0xc0003aebb2, 0x2, 0x2, 0xd00980, 0xc0002d8110)
        /home/user/work/golang/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:766 +0x73
github.com/supplyon/gremcos.(*websocket).Close(0xc0002af1f0, 0x0, 0x0)
        /home/user/work/gremcos/connection.go:198 +0x14e
github.com/supplyon/gremcos.(*client).Close.func1()
        /home/user/work/gremcos/client.go:304 +0x9a
sync.(*Once).doSlow(0xc00035f748, 0xc00057bab8)
        /usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
github.com/supplyon/gremcos.(*client).Close(0xc00035f6b0, 0x0, 0x0)
        /home/user/work/gremcos/client.go:284 +0xed
github.com/supplyon/gremcos.(*client).workerSaveExit(0xc00035f6b0, 0xdc2198, 0xb, 0xc0000427e0)
        /home/user/work/gremcos/client.go:403 +0x4c
panic(0xc6e4e0, 0xee0e90)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc000252510, 0xc0003aba01, 0x0, 0x0, 0x0, 0x7f722e15c008, 0x0)
        /home/user/work/golang/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:610 +0x612
github.com/gorilla/websocket.(*messageWriter).Close(0xc000252510, 0x4305d1, 0xc00057bd20)
        /home/user/work/golang/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:724 +0x62
github.com/gorilla/websocket.(*Conn).beginMessage(0xc00030c9a0, 0xc0003abad0, 0x2, 0x0, 0xc00057bd98)
        /home/user/work/golang/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:473 +0x284
github.com/gorilla/websocket.(*Conn).NextWriter(0xc00030c9a0, 0x2, 0x2, 0xc00057bda8, 0xc00057bdf8, 0xbd9a0f)
        /home/user/work/golang/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:513 +0x53
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc00030c9a0, 0x2, 0xc00056a000, 0xb4, 0xc0, 0x0, 0x14dfb00)
        /home/user/work/golang/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:766 +0x73
github.com/supplyon/gremcos.(*websocket).Write(0xc0002af1f0, 0xc00056a000, 0xb4, 0xc0, 0x0, 0x0)
        /home/user/work/gremcos/connection.go:153 +0x163
github.com/supplyon/gremcos.(*client).writeWorker(0xc00035f6b0, 0xc0000427e0, 0xc0003561e0)
        /home/user/work/gremcos/client.go:323 +0x1d1
created by github.com/supplyon/gremcos.Dial
        /home/user/work/gremcos/client.go:119 +0x103
```

**Comment by ThomasObenaus** [comment]
h1. Hint
When running an example app build with -race the execution environment warns that there is a data race

```
==================
WARNING: DATA RACE
Write at 0x00c0000f21c0 by goroutine 44:
  github.com/gorilla/websocket.(*Conn).SetWriteDeadline()
      /home/user/work/golang/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:781 +0x4b
  github.com/supplyon/gremcos.(*websocket).Write()
      /home/user/work/gremcos/connection.go:149 +0x1a5
  github.com/supplyon/gremcos.(*client).writeWorker()
      /home/user/work/gremcos/client.go:323 +0x22b

Previous write at 0x00c0000f21c0 by goroutine 43:
  github.com/gorilla/websocket.(*Conn).SetWriteDeadline()
      /home/user/work/golang/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:781 +0x4b
  github.com/supplyon/gremcos.(*websocket).Write()
      /home/user/work/gremcos/connection.go:149 +0x1a5
  github.com/supplyon/gremcos.(*client).writeWorker()
      /home/user/work/gremcos/client.go:323 +0x22b

Goroutine 44 (running) created at:
  github.com/supplyon/gremcos.Dial()
      /home/user/work/gremcos/client.go:119 +0x162
  github.com/supplyon/gremcos.(*Cosmos).dial()
      /home/user/work/gremcos/cosmos.go:138 +0x17b
  github.com/supplyon/gremcos.(*Cosmos).dial-fm()
      /home/user/work/gremcos/cosmos.go:137 +0x45
  github.com/supplyon/gremcos.(*pool).Get()
      /home/user/work/gremcos/pool.go:152 +0x558
  github.com/supplyon/gremcos.(*pool).Execute()
      /home/user/work/gremcos/pool.go:285 +0x6f
  github.com/supplyon/gremcos.(*Cosmos).Execute()
      /home/user/work/gremcos/cosmos.go:143 +0x85
  main.initializeServiceLogic.func1()
      /home/user/work/my-app/main.go:45 +0x7e
  github.com/gin-gonic/gin.(*Context).Next()
      /home/user/work/golang/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0xa6
  bitbucket.supplyon.de/scm/shared/go-toolbox.git/apigin.LoggingMiddleWare.LogRequest()
      /home/user/work/golang/pkg/mod/bitbucket.supplyon.de/scm/shared/go-toolbox.git@v0.0.2-0.20200212154030-12eaecd1aab8/apigin/loggerMW.go:32 +0x16e
  bitbucket.supplyon.de/scm/shared/go-toolbox.git/apigin.LoggingMiddleWare.LogRequest-fm()
      /home/user/work/golang/pkg/mod/bitbucket.supplyon.de/scm/shared/go-toolbox.git@v0.0.2-0.20200212154030-12eaecd1aab8/apigin/loggerMW.go:25 +0xa6
  github.com/gin-gonic/gin.(*Context).Next()
      /home/user/work/golang/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0xa6
  github.com/gin-gonic/gin.RecoveryWithWriter.func1()
      /home/user/work/golang/pkg/mod/github.com/gin-gonic/gin@v1.5.0/recovery.go:83 +0x7f
  github.com/gin-gonic/gin.(*Context).Next()
      /home/user/work/golang/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0xa6
  github.com/gin-gonic/gin.(*Engine).handleHTTPRequest()
      /home/user/work/golang/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:403 +0xa45
  github.com/gin-gonic/gin.(*Engine).ServeHTTP()
      /home/user/work/golang/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:364 +0x2f4
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2802 +0xce
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1890 +0x837

Goroutine 43 (running) created at:
  github.com/supplyon/gremcos.Dial()
      /home/user/work/gremcos/client.go:119 +0x162
  github.com/supplyon/gremcos.(*Cosmos).dial()
      /home/user/work/gremcos/cosmos.go:138 +0x17b
  github.com/supplyon/gremcos.(*Cosmos).dial-fm()
      /home/user/work/gremcos/cosmos.go:137 +0x45
  github.com/supplyon/gremcos.(*pool).Get()
      /home/user/work/gremcos/pool.go:152 +0x558
  github.com/supplyon/gremcos.(*pool).Execute()
      /home/user/work/gremcos/pool.go:285 +0x6f
  github.com/supplyon/gremcos.(*Cosmos).Execute()
      /home/user/work/gremcos/cosmos.go:143 +0x85
  main.initializeServiceLogic.func1()
      /home/user/work/my-app/main.go:45 +0x7e
  github.com/gin-gonic/gin.(*Context).Next()
      /home/user/work/golang/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0xa6
  bitbucket.supplyon.de/scm/shared/go-toolbox.git/apigin.LoggingMiddleWare.LogRequest()
      /home/user/work/golang/pkg/mod/bitbucket.supplyon.de/scm/shared/go-toolbox.git@v0.0.2-0.20200212154030-12eaecd1aab8/apigin/loggerMW.go:32 +0x16e
  bitbucket.supplyon.de/scm/shared/go-toolbox.git/apigin.LoggingMiddleWare.LogRequest-fm()
      /home/user/work/golang/pkg/mod/bitbucket.supplyon.de/scm/shared/go-toolbox.git@v0.0.2-0.20200212154030-12eaecd1aab8/apigin/loggerMW.go:25 +0xa6
  github.com/gin-gonic/gin.(*Context).Next()
      /home/user/work/golang/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0xa6
  github.com/gin-gonic/gin.RecoveryWithWriter.func1()
      /home/user/work/golang/pkg/mod/github.com/gin-gonic/gin@v1.5.0/recovery.go:83 +0x7f
  github.com/gin-gonic/gin.(*Context).Next()
      /home/user/work/golang/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0xa6
  github.com/gin-gonic/gin.(*Engine).handleHTTPRequest()
      /home/user/work/golang/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:403 +0xa45
  github.com/gin-gonic/gin.(*Engine).ServeHTTP()
      /home/user/work/golang/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:364 +0x2f4
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2802 +0xce
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1890 +0x837
==================

```

**Comment by ThomasObenaus** [comment]
# Root Cause
* As one can see at [cosmos.go](https://github.com/supplyon/gremcos/blob/aa7f184cf2a240d900c7cd428dbfe3ec72bb020b/cosmos.go#L108) there is one websocket (dialer) created and then used for each new call.
* By doing this only one websocket is created and used inside the pool for all the "clients". But that is problematic the idea was to have a separate websocket for each client to ensure that each call is handled over one websocket. Since anyway (as we see due to the panic) it is not allowed to push multiple packages at the same time through a websocket.

**Comment by mattKorwel** [comment]
@ThomasObenaus I'm getting this error now trying to run concurrent inserts to cosmos.

I was hoping that you might find anything in myset up that I'm doing wrong? If not i can dive in and try and debug further.

I have max connections set to 100. Timeout to 1000 seconds and am running 100 go routines for build import.

Cheers and thanks for all the hard work on this library.

```
panic: concurrent write to websocket connection

goroutine 17204 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0246609f0, 0x1, {0x0, 0x7f44ea521a68, 0x0})
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:610 +0x52b
github.com/gorilla/websocket.(*messageWriter).Close(0xc014202d00)
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:724 +0x45
github.com/gorilla/websocket.(*Conn).beginMessage(0xc02a8ce9a0, 0xc02e1b0750, 0x8)
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:473 +0x42
github.com/gorilla/websocket.(*Conn).NextWriter(0xc02a8ce9a0, 0x8)
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:513 +0x45
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc024660990, 0x438400, {0xc02e0bc606, 0x0, 0x7f4800})
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:766 +0x165
github.com/supplyon/gremcos.(*websocket).Close(0xc014b79ce0)
        /go/pkg/mod/github.com/supplyon/gremcos@v0.1.16/connection.go:225 +0x104
github.com/supplyon/gremcos.(*client).Close.func1()
        /go/pkg/mod/github.com/supplyon/gremcos@v0.1.16/client.go:353 +0x7c
sync.(*Once).doSlow(0x7f44a9afcfd8, 0xc000041000)
        /usr/local/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/supplyon/gremcos.(*client).Close(0xc027b13400)
        /go/pkg/mod/github.com/supplyon/gremcos@v0.1.16/client.go:334 +0x85
github.com/supplyon/gremcos.(*client).workerSaveExit(0xc027b13400, {0x865d0d, 0xa}, 0xc027e866e0)
        /go/pkg/mod/github.com/supplyon/gremcos@v0.1.16/client.go:456 +0x4f
github.com/supplyon/gremcos.(*client).readWorker(0xc027b13400, 0xc013b2a960, 0xc01bf2001c)
        /go/pkg/mod/github.com/supplyon/gremcos@v0.1.16/client.go:419 +0x1e2
created by github.com/supplyon/gremcos.Dial
        /go/pkg/mod/github.com/supplyon/gremcos@v0.1.16/client.go:129 +0x17e
exit status 2

```

Packages
```
go 1.14

require (
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/google/go-cmp v0.5.6 // indirect
	github.com/rs/zerolog v1.18.0
	github.com/shurcooL/githubv4 v0.0.0-20210922025249-6831e00d857f
	github.com/shurcooL/graphql v0.0.0-20200928012149-18c5c3165e3a // indirect
	github.com/supplyon/gremcos v0.1.16
	golang.org/x/net v0.0.0-20211112202133-69e39bad7dc2 // indirect
	golang.org/x/oauth2 v0.0.0-20211104180415-d3ed0bb246c8 // indirect
	golang.org/x/sys v0.0.0-20211116061358-0a5406a5449c // indirect
	google.golang.org/appengine v1.6.7 // indirect
	google.golang.org/protobuf v1.27.1 // indirect
)
```
go env

```
 go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vscode/.cache/go-build"
GOENV="/home/vscode/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspaces/gremlin-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4223308861=/tmp/go-build -gno-record-gcc-switches"
```
