### ISSUE TITLE
Panic on close of closed channel

### ISSUE THREAD

**Issue by ThomasObenaus** [supplyon/gremcos#29]
panic: close of closed channel

goroutine 27 [running]:
github.com/supplyon/gremcos.(*client).Close.func1.1(0x8575c0, 0xc00013c1f0, 0x852cc0, 0xc000152060, 0x3)
        /home/user/work/gremcos/client.go:307 +0xc0
sync.(*Map).Range(0xc000097b30, 0x921190)
        /usr/local/go/src/sync/map.go:333 +0x1c3
github.com/supplyon/gremcos.(*client).Close.func1()
        /home/user/work/gremcos/client.go:304 +0x61
sync.(*Once).doSlow(0xc0000ca6c8, 0xc00014de60)
        /usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
github.com/supplyon/gremcos.(*client).Close(0xc0000ca630, 0x0, 0x0)
        /home/user/work/gremcos/client.go:298 +0xed
github.com/supplyon/gremcos.(*client).workerSaveExit(0xc0000ca630, 0x902049, 0xa, 0xc000156060)
        /home/user/work/gremcos/client.go:419 +0x4c
github.com/supplyon/gremcos.(*client).readWorker(0xc0000ca630, 0xc000156060, 0xc00008a120)
        /home/user/work/gremcos/client.go:367 +0x2e1
created by github.com/supplyon/gremcos.Dial
        /home/user/work/gremcos/client.go:120 +0x13b
exit status 2

**Comment by ThomasObenaus** [comment]
This happens if one wants to connect to azure but provides the wrong credentials (especially password).
