### ISSUE TITLE
Concurrent Write Panics

### ISSUE THREAD

**Issue by mattKorwel** [supplyon/gremcos#94]
@ThomasObenaus I'm getting this error now trying to run concurrent inserts to cosmos.

I was hoping that you might find anything in myset up that I'm doing wrong? If not i can dive in and try and debug further.

I have max connections set to 100. Timeout to 1000 seconds and am running 100 go routines for build import.

Cheers and thanks for all the hard work on this library.

```
panic: concurrent write to websocket connection

goroutine 17204 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0246609f0, 0x1, {0x0, 0x7f44ea521a68, 0x0})
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:610 +0x52b
github.com/gorilla/websocket.(*messageWriter).Close(0xc014202d00)
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:724 +0x45
github.com/gorilla/websocket.(*Conn).beginMessage(0xc02a8ce9a0, 0xc02e1b0750, 0x8)
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:473 +0x42
github.com/gorilla/websocket.(*Conn).NextWriter(0xc02a8ce9a0, 0x8)
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:513 +0x45
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc024660990, 0x438400, {0xc02e0bc606, 0x0, 0x7f4800})
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:766 +0x165
github.com/supplyon/gremcos.(*websocket).Close(0xc014b79ce0)
        /go/pkg/mod/github.com/supplyon/gremcos@v0.1.16/connection.go:225 +0x104
github.com/supplyon/gremcos.(*client).Close.func1()
        /go/pkg/mod/github.com/supplyon/gremcos@v0.1.16/client.go:353 +0x7c
sync.(*Once).doSlow(0x7f44a9afcfd8, 0xc000041000)
        /usr/local/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/supplyon/gremcos.(*client).Close(0xc027b13400)
        /go/pkg/mod/github.com/supplyon/gremcos@v0.1.16/client.go:334 +0x85
github.com/supplyon/gremcos.(*client).workerSaveExit(0xc027b13400, {0x865d0d, 0xa}, 0xc027e866e0)
        /go/pkg/mod/github.com/supplyon/gremcos@v0.1.16/client.go:456 +0x4f
github.com/supplyon/gremcos.(*client).readWorker(0xc027b13400, 0xc013b2a960, 0xc01bf2001c)
        /go/pkg/mod/github.com/supplyon/gremcos@v0.1.16/client.go:419 +0x1e2
created by github.com/supplyon/gremcos.Dial
        /go/pkg/mod/github.com/supplyon/gremcos@v0.1.16/client.go:129 +0x17e
exit status 2

```

Packages
```
go 1.14

require (
	github.com/golang/protobuf v1.5.2 // indirect
	github.com/google/go-cmp v0.5.6 // indirect
	github.com/rs/zerolog v1.18.0
	github.com/shurcooL/githubv4 v0.0.0-20210922025249-6831e00d857f
	github.com/shurcooL/graphql v0.0.0-20200928012149-18c5c3165e3a // indirect
	github.com/supplyon/gremcos v0.1.16
	golang.org/x/net v0.0.0-20211112202133-69e39bad7dc2 // indirect
	golang.org/x/oauth2 v0.0.0-20211104180415-d3ed0bb246c8 // indirect
	golang.org/x/sys v0.0.0-20211116061358-0a5406a5449c // indirect
	google.golang.org/appengine v1.6.7 // indirect
	google.golang.org/protobuf v1.27.1 // indirect
)
```
go env

```
 go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vscode/.cache/go-build"
GOENV="/home/vscode/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/workspaces/gremlin-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4223308861=/tmp/go-build -gno-record-gcc-switches"
```

had mentioned this as a comment on a closed issue, elevating here as the erro seems pretty reproduceable. 

https://github.com/supplyon/gremcos/issues/20#issuecomment-973888074

**Comment by ThomasObenaus** [comment]
Hi @mattKorwel,
thanks for posting that issue. 
Could you please provide a short code snippet that reproduces the issue if possible?
This would help me a lot.

**Comment by mattKorwel** [comment]
Hi! just saw your follow up. Will add a snippet as soon as i get a chance. thanks
